substitutions:
  devicename: temp-display
  gpio_spi_clk_pin: GPIO13
  gpio_spi_mosi_pin: GPIO14
  gpio_cs_pin: GPIO15
  gpio_busy_pin: GPIO25
  gpio_reset_pin: GPIO26
  gpio_dc_pin: GPIO27

esphome:
  name: temp-display
  platform: ESP32
  board: esp32dev
  on_boot:
    priority: -100
    then:
      - switch.turn_on: statusLED
      - delay: 1s
      - switch.turn_off: statusLED

wifi:
  networks:
  - ssid: //your data
    password: //your data
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: //your data
    password: //your data

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: //your data

ota:
  password: //your data

spi:
  clk_pin: $gpio_spi_clk_pin
  mosi_pin: $gpio_spi_mosi_pin
  id: epaper_display
  


#########################-----TIME-----#########################

time:
  - platform: homeassistant
    timezone: Asia/Jerusalem
    id: current_time
    on_time_sync:
      - component.update: uptime_timestamp

#########################-----SWITCHES-----#########################

switch:
  - platform: restart
    name: "$devicename Restart"
    id: restartesp

  - platform: gpio
    id: statusLED
    name: "$devicename Status LED"
    pin:
      number: GPIO2
      mode: OUTPUT
    restore_mode: ALWAYS_OFF

#########################-----SENSORS-----#########################

binary_sensor:
  - platform: status
    name: "$devicename Status"

  - platform: homeassistant
    name: "Out Temp Rising"
    entity_id: binary_sensor.temp_rising
    id: out_temp_rising
    internal: true

  - platform: homeassistant
    name: "Out Temp Failing"
    entity_id: binary_sensor.temp_falling
    id: out_temp_failing
    internal: true

sensor:
  - platform: uptime
    name: "$devicename Uptime Sec"
    id: uptime_sec
    internal: true

  - platform: wifi_signal
    name: "$devicename WiFi Signal"
    update_interval: 120s

  - platform: template
    id: uptime_timestamp
    name: "$devicename Uptime"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      static float timestamp = (
        id(current_time).utcnow().timestamp - id(uptime_sec).state
      );
      return timestamp;

  - platform: homeassistant
    name: "Bedroom floor Temp. from HA"
    entity_id: sensor.bedroom_up_sense_temperature
    unit_of_measurement: "°"
    accuracy_decimals: 1
    id: average_bedroom_temp
    internal: true

  - platform: homeassistant
    name: "Bedroom floor Hum. from HA"
    entity_id: sensor.bedroom_up_sense_humidity_level
    unit_of_measurement: "%"
    accuracy_decimals: 0
    id: average_bedroom_hum
    internal: true

  - platform: homeassistant
    name: "Livingroom floor Temp. from HA"
    entity_id: sensor.lumi_lumi_airmonitor_acn01_temperature
    unit_of_measurement: "°"
    accuracy_decimals: 1
    id: average_livingroom_temp
    internal: true

  - platform: homeassistant
    name: "Livingroom floor Hum. from HA"
    entity_id: sensor.lumi_lumi_airmonitor_acn01_humidity
    unit_of_measurement: "%"
    accuracy_decimals: 0
    id: average_livingroom_hum
    internal: true

  - platform: homeassistant
    name: "Livingroom floor TVOC from HA"
    entity_id: sensor.lumi_lumi_airmonitor_acn01_voc_level
    unit_of_measurement: "ppb"
    accuracy_decimals: 0
    id: voc_index
    internal: true

  - platform: homeassistant
    name: "Outdoor Temp. from HA"
    entity_id: sensor.openweathermap_temperature
    unit_of_measurement: "°"
    accuracy_decimals: 1
    id: outdoor_temp
    internal: true

  - platform: homeassistant
    name: "Outdoor Hum. from HA"
    entity_id: sensor.openweathermap_humidity
    unit_of_measurement: "%"
    accuracy_decimals: 0
    id: outdoor_hum
    internal: true

  - platform: homeassistant
    name: "Day1 Temp Forecast"
    entity_id: sensor.day_1_temp
    id: forcast_1_temp
    internal: true

  - platform: homeassistant
    name: "Day2 Temp Forecast"
    entity_id: sensor.day_2_temp
    id: forcast_2_temp
    internal: true

  - platform: homeassistant
    name: "Day3 Temp Forecast"
    entity_id: sensor.day_3_temp
    id: forcast_3_temp
    internal: true

#########################-----TEXT SENSORS-----#########################

text_sensor:
  - platform: homeassistant
    name: "Day1 Weather Icon"
    entity_id: sensor.day_1_forecast
    id: forcast_1
    internal: true

  - platform: homeassistant
    name: "Day2 Weather Icon"
    entity_id: sensor.day_2_forecast
    id: forcast_2
    internal: true

  - platform: homeassistant
    name: "Day3 Weather Icon"
    entity_id: sensor.day_3_forecast
    id: forcast_3
    internal: true
  
  - platform: homeassistant
    name: "Day1 name"
    entity_id: sensor.day_1_dow
    id: forcast_dow_1
    internal: true

  - platform: homeassistant
    name: "Day2 name"
    entity_id: sensor.day_2_dow
    id: forcast_dow_2
    internal: true

  - platform: homeassistant
    name: "Day3 name"
    entity_id: sensor.day_3_dow
    id: forcast_dow_3
    internal: true

#########################-----DISPLAY-----#########################      
      
display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: $gpio_cs_pin
    busy_pin: $gpio_busy_pin
    reset_pin: $gpio_reset_pin
    dc_pin: $gpio_dc_pin
    model: 4.20in # 300x400
    rotation: 0°
    update_interval: 60s
    lambda: |-
      ESP_LOGI("display", "Updating...");
      
      // OUTSIDE
      it.printf(7, 19, id(font_medium_20), TextAlign::BASELINE_LEFT, "Outside");
      it.line(81, 18, 290, 18);

      it.strftime(305, 19, id(font_medium_20), TextAlign::BASELINE_LEFT, "%A", id(current_time).now());
      it.strftime(305, 44, id(font_medium_20), TextAlign::BASELINE_LEFT, "%d %b. %y", id(current_time).now());
      
      it.printf(9, 82, id(icon_font_40), TextAlign::BASELINE_LEFT, "\U000F050F"); 
      if (id(outdoor_temp).has_state()) {
          it.printf(186, 82, id(font_regular_65), TextAlign::BASELINE_RIGHT, "%.1f°", id(outdoor_temp).state);
      }
      it.printf(179, 86, id(icon_font_35), TextAlign::BASELINE_LEFT, "\U000F058E"); 
      if (id(outdoor_hum).has_state()) {
          it.printf(262, 84, id(font_regular_45), TextAlign::BASELINE_RIGHT, "%2.0f", id(outdoor_hum).state);
          it.printf(265, 84, id(font_regular_30), TextAlign::BASELINE_LEFT, "%%");
      }
      
      if (id(out_temp_rising).has_state() && id(out_temp_failing).has_state()) {
          if (id(out_temp_rising).state == true) {
              it.printf(185, 84, id(icon_font_20), TextAlign::BASELINE_RIGHT, "\U000F005C"); 
          }
          if (id(out_temp_failing).state == true) {
              it.printf(185, 84, id(icon_font_20), TextAlign::BASELINE_RIGHT, "\U000F0043"); 
          }
      }
      
      // INSIDE
      it.printf(7, 117, id(font_medium_20), TextAlign::BASELINE_LEFT, "Inside");
      it.line(64, 116, 290, 116);

      // Livingroom
      it.printf(18, 167, id(icon_font_30), TextAlign::BASELINE_LEFT, "\U000F04B9"); 
      
      it.printf(60, 164, id(icon_font_30), TextAlign::BASELINE_LEFT, "\U000F050F"); 
      if (id(average_livingroom_temp).has_state()) {
          it.printf(190, 165, id(font_regular_45), TextAlign::BASELINE_RIGHT, "%.1f°", id(average_livingroom_temp).state);
      }
      it.printf(195, 166, id(icon_font_25), TextAlign::BASELINE_LEFT, "\U000F058E"); 
      if (id(average_livingroom_hum).has_state()) {
          it.printf(262, 165, id(font_regular_35), TextAlign::BASELINE_RIGHT, "%.0f", id(average_livingroom_hum).state);
          it.printf(265, 165, id(font_regular_30), TextAlign::BASELINE_LEFT, "%%");
      }

      // Bedroom
      it.printf(18, 217, id(icon_font_30), TextAlign::BASELINE_LEFT, "\U000F02E3"); 
      
      it.printf(60, 214, id(icon_font_30), TextAlign::BASELINE_LEFT, "\U000F050F");
      if (id(average_bedroom_temp).has_state()) {
          it.printf(190, 215, id(font_regular_45), TextAlign::BASELINE_RIGHT, "%.1f°", id(average_bedroom_temp).state);
      }
      it.printf(195, 216, id(icon_font_25), TextAlign::BASELINE_LEFT, "\U000F058E"); 
      if (id(average_bedroom_hum).has_state()) {
          it.printf(262, 215, id(font_regular_35), TextAlign::BASELINE_RIGHT, "%.0f", id(average_bedroom_hum).state);
          it.printf(265, 215, id(font_regular_30), TextAlign::BASELINE_LEFT, "%%");
      }

      //FORECAST
      if (id(forcast_1).has_state() && id(forcast_1_temp).has_state() && id(forcast_2).has_state() && id(forcast_2_temp).has_state() && id(forcast_3).has_state() && id(forcast_3_temp).has_state()) {
          std::map<std::string, std::string> weather_state { 
            { "clear-night", "\U000F0594" },
            { "cloudy", "\U000F0590" },
            { "exceptional", "\U000F05D6" },
            { "fog", "\U000F0591" },                
            { "hail", "\U000F0592" },               
            { "lightning", "\U000F0593" },              
            { "lightning-rainy", "\U000F067E" },                
            { "partlycloudy", "\U000F0595"},                 
            { "pouring", "\U000F0596" },  
            { "rainy", "\U000F0597" },
            { "snowy", "\U000F0598" },
            { "snowy-rainy", "\U000F067F" },
            { "sunny", "\U000F0599" },
            { "windy", "\U000F059D" },
            { "windy-variant", "\U000F059E" }
          };

          it.printf(305, 87, id(font_medium_20), TextAlign::BASELINE_LEFT, "%s.", id(forcast_dow_1).state.c_str());
          it.line(348, 86, 393, 86);
          it.printf(303, 116, id(icon_font_25), TextAlign::BASELINE_LEFT, weather_state[id(forcast_1).state.c_str()].c_str());
          it.printf(393, 115, id(font_regular_30), TextAlign::BASELINE_RIGHT, "%.1f°", id(forcast_1_temp).state);
          it.printf(305, 137, id(font_medium_20), TextAlign::BASELINE_LEFT, "%s.", id(forcast_dow_2).state.c_str());
            it.line(348, 136, 393, 136);
          it.printf(303, 166, id(icon_font_25), TextAlign::BASELINE_LEFT, weather_state[id(forcast_2).state.c_str()].c_str());
          it.printf(393, 165, id(font_regular_30), TextAlign::BASELINE_RIGHT, "%.1f°", id(forcast_2_temp).state);
          it.printf(305, 187, id(font_medium_20), TextAlign::BASELINE_LEFT, "%s.", id(forcast_dow_3).state.c_str());
            it.line(348, 186, 393, 186);
          it.printf(303, 216, id(icon_font_25), TextAlign::BASELINE_LEFT, weather_state[id(forcast_3).state.c_str()].c_str());
          it.printf(393, 215, id(font_regular_30), TextAlign::BASELINE_RIGHT, "%.1f°", id(forcast_3_temp).state);
        }
   
  
      // TVOC
      it.printf(7, 251, id(font_medium_20), TextAlign::BASELINE_LEFT, "TVOC");
      it.line(60, 250, 143, 250);

      if (id(voc_index).has_state()) {
        if (id(voc_index).state <= 65) {
            it.printf(15, 285, id(icon_font_25), TextAlign::BASELINE_LEFT, "\U000F0e62\U000F0e62\U000F0e62\U000F0e62\U000F0e62"); //EXCELLENT
        } else if (id(voc_index).state <= 220) {
            it.printf(15, 285, id(icon_font_25), TextAlign::BASELINE_LEFT, "\U000F0e62\U000F0e62\U000F0e62\U000F0e62\U000F0e63"); //GOOD        
        } else if (id(voc_index).state <= 660) {
            it.printf(15, 285, id(icon_font_25), TextAlign::BASELINE_LEFT, "\U000F0e62\U000F0e62\U000F0e62\U000F0e63\U000F0e63"); //FAIR
        } else if (id(voc_index).state <= 2200) {
           it.printf(15, 285, id(icon_font_25), TextAlign::BASELINE_LEFT, "\U000F0e62\U000F0e62\U000F0e63\U000F0e63\U000F0e63"); //POOR
        } else {
           it.printf(15, 285, id(icon_font_25), TextAlign::BASELINE_LEFT, "\U000F0e62\U000F0e63\U000F0e63\U000F0e63\U000F0e63"); //INADEQUATE
        }         
      } else {
        it.printf(15, 285, id(icon_font_25), TextAlign::BASELINE_LEFT, "\U000F0e63\U000F0e63\U000F0e63\U000F0e63\U000F0e63");
      }
 
       // TIME

      it.strftime(390, 293, id(font_regular_65), TextAlign::BASELINE_RIGHT, "%H:%M", id(current_time).now());



      
#########################-----FONTS-----#########################       


font:
  - file: 'fonts/Kanit-Medium.ttf'
    id: font_medium_20
    size: 20
    glyphs:
      ['&', '@', '!', ',', '.', '"', '%', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z', '/', 'é']

  - file: 'fonts/Kanit-Regular.ttf'
    id: font_regular_30
    size: 30
    glyphs: 
      ['&', '@', '!', ',', '.', '"', '%', '+', '-', '_', ':', '°', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E',
       'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
       'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ', 'a', 'b', 'c', 'd', 'e', 'f',
       'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
       'u', 'v', 'w', 'x', 'y', 'z', '/', 'è']

  - file: 'fonts/Kanit-Regular.ttf'
    id: font_regular_35
    size: 35
    glyphs: 
      ['!', ',', '.', '"', '%', '-', '_', ':', '°', '/',
       '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ' ']

  - file: 'fonts/Kanit-Regular.ttf'
    id: font_regular_45
    size: 45
    glyphs: 
      ['!', ',', '.', '"', '%', '-', '_', ':', '°', '/',
       '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ' ']

  - file: 'fonts/Kanit-Regular.ttf'
    id: font_regular_65
    size: 65
    glyphs: 
      ['!', ',', '.', '"', '%', '-', '_', ':', '°', '/',
       '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ' ']

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icon_font_20
    size: 20
    glyphs: [
      "\U000F0043", # mdi-arrow-bottom-right
      "\U000F005C"  # mdi-arrow-top-right
      ]

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icon_font_25
    size: 25
    glyphs: [
      "\U000F058E", # mdi-water-percent
      "\U000F0E62", # mdi-seed
      "\U000F0E63", # mdi-seed-outline
      "\U000F002A", # mdi-alert-outline
      "\U000F0594", # mdi-weather-night - clear-night
      "\U000F0590", # mdi-weather-cloudy
      "\U000F05D6", # mdi-alert-circle-outline - exeptionnal
      "\U000F0591", # mdi-weather-fog
      "\U000F0592", # mdi-weather-hail
      "\U000F0593", # mdi-weather-lightning
      "\U000F067E", # mdi-weather-lightning-rainy
      "\U000F0595", # mdi-weather-partly-cloudy
      "\U000F0596", # mdi-weather-pouring
      "\U000F0597", # mdi-weather-rainy
      "\U000F0598", # mdi-weather-snowy
      "\U000F067F", # mdi-weather-snowy-rainy
      "\U000F0599", # mdi-weather-sunny
      "\U000F059D", # mdi-weather-windy
      "\U000F059E"  # mdi-weather-windy-variant
      ]

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icon_font_30
    size: 30
    glyphs: [
      "\U000F050F", # mdi-thermometer
      "\U000F04B9", # mdi-sofa
      "\U000F02E3"  # mdi-bed
      ]

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icon_font_35
    size: 35
    glyphs: ["\U000F058E"]  # mdi-water-percent

  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icon_font_40
    size: 40
    glyphs: ["\U000F050F"] # mdi-thermometer
